FROM ubuntu:24.04

############################################################

# 更新包清單並安裝 sudo
RUN apt-get update && apt-get install -y sudo adduser

# 將 ubuntu 加入 sudo 群組
RUN echo "ubuntu:ubuntu" | chpasswd && \
    adduser ubuntu sudo

# 設置無密碼 sudo
RUN echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu

############################################################

# 更新套件清單並安裝必要的工具
RUN apt-get update && \
    apt-get install -y \
    wget \
    bzip2 \
    ca-certificates \
    curl \
    git \
    build-essential \
    python3-dev

RUN apt-get install -y pkg-config libmysqlclient-dev 
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# 下載並安裝 Miniconda
RUN wget -qO /tmp/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh

# 設定環境變數
ENV PATH /opt/conda/bin:$PATH
# 初始化 Conda
RUN conda init
# 創建新的 Conda 環境
RUN conda create -n workspace python=3.10 -y
# 設定環境變數，使 workspace 成為預設環境
ENV PATH /opt/conda/envs/workspace/bin:$PATH
RUN echo "conda activate workspace" >> ~/.bashrc
# 防止 Python 寫入 .pyc 文件
ENV PYTHONDONTWRITEBYTECODE=1

# 建立應用目錄
RUN mkdir /app

############################################################

# 安裝 llama-index 依賴
RUN pip install 'llama-index==0.12.9' && \
    pip install 'llama-index-llms-ollama==0.5.0' && \
    pip install 'llama-index-embeddings-huggingface==0.4.0'

############################################################

# 安裝 FastAPI 依賴
### 主套件
RUN pip install 'fastapi==0.115.6'
### Web 框架
RUN pip install 'starlette==0.41.3'
### 數據驗證
RUN pip install 'pydantic==2.10.4'
### ASGI + WSGI
RUN pip install 'uvicorn==0.34.0'
RUN pip install 'gunicorn==23.0.0'
### 解析 multipart 表單
RUN pip install 'python-multipart==0.0.20'
### 驗證 email 格式
RUN pip install 'email-validator==2.2.0'
### 資料庫異步連接
RUN pip install 'databases==0.9.0'
RUN apt update && apt install -y libmariadb-dev
RUN pip install 'mariadb==1.1.11'
RUN pip install 'mysqlclient==2.1.1'
RUN pip install 'PyMySQL==1.1.1'
RUN pip install 'aiomysql==0.2.0'
### 資料庫遷移
RUN pip install 'sqlalchemy==2.0.36' 'alembic==1.14.0' 
### 同步與異步測試工具
RUN pip install 'pytest==8.3.4' 'pytest-asyncio==0.25.1'
### 異步 Redis
RUN pip install 'aioredis==2.0.1'
### 登入
RUN pip install 'httpx==0.27.2' 'python-dotenv==1.0.1'
############################################################