FROM ubuntu:noble

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:1

# 安裝 X11 + GPU + Steam
RUN dpkg --add-architecture i386 && \
    apt update && \
    apt install -y \
        sudo wget \
        locales \
        dbus dbus-x11 \
        at-spi2-core \
        x11-utils \
        mesa-utils \
        steam-installer \
        xserver-xorg \
        xserver-xorg-core \
        xserver-xorg-input-all \
        xserver-xorg-video-all \
        libgl1 \
        libegl1 \
        x11-xserver-utils && \
    locale-gen zh_TW.UTF-8 && \
    update-locale LANG=zh_TW.UTF-8 && \
    apt clean && rm -rf /var/lib/apt/lists/*

# 新增使用者
RUN useradd -m user && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER user
WORKDIR /home/user