name: judger-runner ruby

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Ruby Images
      run: |
        docker build --pull --no-cache -f judger-runner/ruby/Dockerfile --build-arg RUBY_TAG=3.3 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-3.3 .
        docker build --pull --no-cache -f judger-runner/ruby/Dockerfile --build-arg RUBY_TAG=3.4 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-3.4 .
        docker build --pull --no-cache -f judger-runner/ruby/Dockerfile --build-arg RUBY_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-latest .
        
    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-3.3
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-3.4
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-latest