name: judger-runner node

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Node.js Images
      run: |
        docker build --pull --no-cache -f judger-runner/node/Dockerfile --build-arg NODE_TAG=18-alpine -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-18 .
        docker build --pull --no-cache -f judger-runner/node/Dockerfile --build-arg NODE_TAG=20-alpine -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-20 .
        docker build --pull --no-cache -f judger-runner/node/Dockerfile --build-arg NODE_TAG=22-alpine -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-22 .
        docker build --pull --no-cache -f judger-runner/node/Dockerfile --build-arg NODE_TAG=lts-alpine -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-lts .
    
    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-18
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-20
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-22
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:node-lts