name: judger-runner php

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Golang Images
      run: |
        docker build --pull --no-cache -f judger-runner/php/Dockerfile --build-arg PHP_TAG=8.2-bookworm -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-8.2 .
        docker build --pull --no-cache -f judger-runner/php/Dockerfile --build-arg PHP_TAG=8.3-bookworm -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-8.3 .
        docker build --pull --no-cache -f judger-runner/php/Dockerfile --build-arg PHP_TAG=8.4-bookworm -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-8.4 .
        docker build --pull --no-cache -f judger-runner/php/Dockerfile --build-arg PHP_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-latest .
        
    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-8.2
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-8.3
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-8.4
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:php-latest