name: judger-runner golang

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Golang Images
      run: |
        docker build --pull --no-cache -f judger-runner/golang/Dockerfile --build-arg GO_TAG=1.24-bookworm -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:golang-1.24 .
        docker build --pull --no-cache -f judger-runner/golang/Dockerfile --build-arg GO_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:golang-latest .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:golang-1.24
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:golang-latest