name: judger-runner kotlin

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Kotlin Images
      run: |
        docker build --pull --no-cache -f judger-runner/kotlin/Dockerfile --build-arg KOTLIN_TAG=1.3-alpine -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:kotlin-1.3-alpine .
        docker build --pull --no-cache -f judger-runner/kotlin/Dockerfile --build-arg KOTLIN_TAG=1.4-alpine -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:kotlin-1.4-alpine .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:kotlin-1.3-alpine
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:kotlin-1.4-alpine