name: judger-runner jdk

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build JDK Images
      run: |
        docker build --pull --no-cache -f judger-runner/jdk/Dockerfile --build-arg JDK_TAG=11 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:jdk-11 .
        docker build --pull --no-cache -f judger-runner/jdk/Dockerfile --build-arg JDK_TAG=17 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:jdk-17 .
        docker build --pull --no-cache -f judger-runner/jdk/Dockerfile --build-arg JDK_TAG=21 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:jdk-21 .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:jdk-11
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:jdk-17
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:jdk-21