name: judger-runner rust

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Rust Images
      run: |
        docker build --pull --no-cache -f judger-runner/rust/Dockerfile --build-arg RUST_TAG=1.88-bookworm -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:rust-1.88 .
        docker build --pull --no-cache -f judger-runner/rust/Dockerfile --build-arg RUST_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:rust-latest .
    
    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:rust-1.88
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:rust-latest
    
    - name: Remove images
      run: |
        docker rmi ${{ secrets.DOCKER_USERNAME }}/judger-runner:rust-1.88
        docker rmi ${{ secrets.DOCKER_USERNAME }}/judger-runner:rust-latest
    
    
    - name: Build Go Images
      run: |
        docker build --pull --no-cache -f judger-runner/go/Dockerfile --build-arg GO_TAG=1.24-bookworm -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:go-1.24 .
        docker build --pull --no-cache -f judger-runner/go/Dockerfile --build-arg GO_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:go-latest .
    
    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:go-1.24
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:go-latest
    
    
    - name: Remove images
      run: |
        docker rmi ${{ secrets.DOCKER_USERNAME }}/judger-runner:go-1.24
        docker rmi ${{ secrets.DOCKER_USERNAME }}/judger-runner:go-latest
    
    
    - name: Build Ruby Images
      run: |
        docker build --pull --no-cache -f judger-runner/ruby/Dockerfile --build-arg RUBY_TAG=3.3 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-3.3 .
        docker build --pull --no-cache -f judger-runner/ruby/Dockerfile --build-arg RUBY_TAG=3.4 -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-3.4 .
        docker build --pull --no-cache -f judger-runner/ruby/Dockerfile --build-arg RUBY_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:ruby-latest .