name: judger-runner python

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Python Images
      run: |
        docker build --pull --no-cache -f judger-runner/python/Dockerfile --build-arg PYTHON_TAG=3.9-slim -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.9 .
        docker build --pull --no-cache -f judger-runner/python/Dockerfile --build-arg PYTHON_TAG=3.10-slim -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.10 .
        docker build --pull --no-cache -f judger-runner/python/Dockerfile --build-arg PYTHON_TAG=3.11-slim -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.11 .
        docker build --pull --no-cache -f judger-runner/python/Dockerfile --build-arg PYTHON_TAG=3.12-slim -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.12 .
        docker build --pull --no-cache -f judger-runner/python/Dockerfile --build-arg PYTHON_TAG=3.13-slim -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.13 .
        docker build --pull --no-cache -f judger-runner/python/Dockerfile --build-arg PYTHON_TAG=latest -t ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-latest .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.9
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.10
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.11
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.12
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-3.13
        docker push ${{ secrets.DOCKER_USERNAME }}/judger-runner:python-latest
