name: judger-runner sqlite

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build SQLite Images
      run: |
        docker build --pull --no-cache -f judger-runner/sqlite/Dockerfile --build-arg ALPINE_ARG=3.18 -t tsukisama9292/judger-runner:sqlite .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push tsukisama9292/judger-runner:sqlite