name: judger-runner gcc

on:
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build GCC Images
      run: |
        docker build --pull --no-cache -f judger-runner/gcc/Dockerfile --build-arg GCC_TAG=14-bookworm -t tsukisama9292/judger-runner:gcc-14 .
        docker build --pull --no-cache -f judger-runner/gcc/Dockerfile --build-arg GCC_TAG=15-bookworm -t tsukisama9292/judger-runner:gcc-15 .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push tsukisama9292/judger-runner:gcc-14
        docker push tsukisama9292/judger-runner:gcc-15