name: Kasm Ubuntu Jammy dind 1.16.1

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build --pull --no-cache -f kasm_workspace/ubuntu/1.16.1/dockerfile.jammy-dind -t ${{ secrets.DOCKER_USERNAME }}/ubuntu-jammy-dind:1.16.1-rolling-daily .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/ubuntu-jammy-dind:1.16.1-rolling-daily
  
  pull:
    needs: build
    runs-on: rtx4090

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull the Docker image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/ubuntu-jammy-dind:1.16.1-rolling-daily