name: LANGCHAIN IMAGE

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: langchain fastapi image
      run: |
        docker build --pull --no-cache -f dockerfile.langchain -t ${{ secrets.DOCKER_USERNAME }}/server:langchain-fastapi-rolling .
        docker push ${{ secrets.DOCKER_USERNAME }}/server:langchain-fastapi-rolling
        # docker image rm ${{ secrets.DOCKER_USERNAME }}/server:langchain-fastapi-rolling
        # docker system prune -f
