name: Online Judge Images

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build judge images
      run: |
        docker build --pull --no-cache -f online_judge/dockerfile.ubuntu_cpp -t ${{ secrets.DOCKER_USERNAME }}/judge:cpp-rolling .
        docker build --pull --no-cache -f online_judge/dockerfile.debian_python -t ${{ secrets.DOCKER_USERNAME }}/judge:python-rolling .
        docker build --pull --no-cache -f online_judge/dockerfile.debian_java -t ${{ secrets.DOCKER_USERNAME }}/judge:java-rolling .

    - name: Push the Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/judge:cpp-rolling
        docker push ${{ secrets.DOCKER_USERNAME }}/judge:python-rolling
        docker push ${{ secrets.DOCKER_USERNAME }}/judge:java-rolling
